FROM mysql:8.0.22  

# Variables propias de la imagen de MySQL
ENV MYSQL_ROOT_PASSWORD UserServiceRoot123*
ENV MYSQL_DATABASE user-microservice-db
ENV MYSQL_USER user_service_user
ENV MYSQL_PASSWORD UserService123*

EXPOSE 3306
